package main

import (
	"os"
	"path/filepath"
	"reflect"
	"testing"
	"time"
)

func TestParseUnifiedDiffCollectsOnlyAddedGoLines(t *testing.T) {
	changed, err := parseUnifiedDiff([]byte(`diff --git a/internal/a.go b/internal/a.go
--- a/internal/a.go
+++ b/internal/a.go
@@ -2,0 +3,2 @@
+first
+second
@@ -9,2 +10 @@ old
-old
+replacement
diff --git a/docs/readme.md b/docs/readme.md
--- a/docs/readme.md
+++ b/docs/readme.md
@@ -1,0 +2 @@
+ignored
`))
	if err != nil {
		t.Fatal(err)
	}
	want := map[int]struct{}{3: {}, 4: {}, 10: {}}
	if !reflect.DeepEqual(changed["internal/a.go"], want) ||
		changed["docs/readme.md"] != nil {
		t.Fatalf("changed = %#v", changed)
	}
}

func TestReadCoverageProfileNormalizesAndMergesBlocks(t *testing.T) {
	root := t.TempDir()
	path := filepath.Join(root, "coverage.out")
	value := []byte(`mode: atomic
example.com/product/internal/a.go:3.1,4.2 2 0
example.com/product/internal/a.go:3.1,4.2 2 1
example.com/product/internal/a.go:10.1,10.8 1 0
example.com/product/internal/a.go:11.1,11.1 0 0
`)
	if err := os.WriteFile(path, value, 0o600); err != nil {
		t.Fatal(err)
	}
	blocks, err := readCoverageProfile(
		path,
		root,
		"example.com/product",
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(blocks) != 2 || blocks[0].path != "internal/a.go" ||
		!blocks[0].covered || blocks[0].statements != 2 ||
		blocks[1].covered {
		t.Fatalf("blocks = %+v", blocks)
	}
}

func TestMergeCoverageBlocksCreditsAnyProfile(t *testing.T) {
	first := coverageBlock{
		path: "internal/a.go", startLine: 3, endLine: 4, statements: 2,
	}
	second := first
	second.covered = true
	blocks, err := mergeCoverageBlocks([]coverageBlock{first}, []coverageBlock{second})
	if err != nil || len(blocks) != 1 || !blocks[0].covered {
		t.Fatalf("blocks = %+v, error = %v", blocks, err)
	}
	conflict := second
	conflict.statements = 3
	if _, err := mergeCoverageBlocks(
		[]coverageBlock{first}, []coverageBlock{conflict},
	); err == nil {
		t.Fatal("accepted conflicting coverage blocks")
	}
}

func TestBuildReportCountsChangedStatementsAndExclusions(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, root, "internal/a.go", "package internal\nfunc a() {}\n")
	writeTestFile(t, root, "internal/a_test.go", "package internal\n")
	writeTestFile(
		t,
		root,
		"internal/generated.go",
		"// Code generated by fixture. DO NOT EDIT.\npackage internal\n",
	)
	changed := lineSet{
		"internal/a.go":         {2: {}},
		"internal/a_test.go":    {1: {}},
		"internal/generated.go": {2: {}},
	}
	result, err := buildReport(root, changed, []coverageBlock{
		{path: "internal/a.go", startLine: 2, endLine: 2, statements: 2, covered: true},
		{path: "internal/a.go", startLine: 2, endLine: 3, statements: 1},
		{path: "internal/a_test.go", startLine: 1, endLine: 1, statements: 10},
		{path: "internal/generated.go", startLine: 2, endLine: 2, statements: 10},
	}, nil)
	if err != nil {
		t.Fatal(err)
	}
	if result.covered != 2 || result.statements != 3 ||
		len(result.files) != 1 ||
		!reflect.DeepEqual(result.files[0].uncoveredChangedLine, []int{2}) {
		t.Fatalf("report = %+v", result)
	}
}

func TestBuildReportRejectsChangedFileMissingFromProfiles(t *testing.T) {
	root := t.TempDir()
	writeTestFile(
		t,
		root,
		"internal/a.go",
		"package internal\nfunc a() { println(\"a\") }\n",
	)
	_, err := buildReport(
		root,
		lineSet{"internal/a.go": {2: {}}},
		nil,
		nil,
	)
	if err == nil {
		t.Fatal("accepted a changed Go file absent from coverage profiles")
	}
	writeTestFile(t, root, "internal/a.go", "package internal\ntype A string\n")
	if _, err := buildReport(
		root,
		lineSet{"internal/a.go": {2: {}}},
		nil,
		nil,
	); err != nil {
		t.Fatalf("declaration-only file error = %v", err)
	}
}

func TestReadExclusionsRequiresReasonAndUnexpiredReview(t *testing.T) {
	root := t.TempDir()
	path := filepath.Join(root, "exclusions.txt")
	value := "internal/tools/fixture/\t2027-01-31\tCovered by external process tests.\n"
	if err := os.WriteFile(path, []byte(value), 0o600); err != nil {
		t.Fatal(err)
	}
	exclusions, err := readExclusions(
		path,
		root,
		time.Date(2026, 8, 15, 12, 0, 0, 0, time.UTC),
	)
	if err != nil || len(exclusions) != 1 ||
		!excluded("internal/tools/fixture/main.go", exclusions) ||
		excluded("internal/tools/other/main.go", exclusions) {
		t.Fatalf("exclusions = %+v, error = %v", exclusions, err)
	}
	if _, err := readExclusions(
		path,
		root,
		time.Date(2027, 2, 1, 0, 0, 0, 0, time.UTC),
	); err == nil {
		t.Fatal("accepted an expired exclusion")
	}
}

func TestDecodeDiffPathRejectsTraversal(t *testing.T) {
	if _, err := decodeDiffPath("b/../../outside.go"); err == nil {
		t.Fatal("accepted a path outside the repository")
	}
	if path, err := decodeDiffPath(`"b/internal/path with space.go"`); err != nil ||
		path != "internal/path with space.go" {
		t.Fatalf("quoted path = %q, %v", path, err)
	}
}

func writeTestFile(t *testing.T, root, path, value string) {
	t.Helper()
	absolute := filepath.Join(root, filepath.FromSlash(path))
	if err := os.MkdirAll(filepath.Dir(absolute), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(absolute, []byte(value), 0o600); err != nil {
		t.Fatal(err)
	}
}
